# Generated by Django 3.1.6 on 2021-02-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_skills', '0002_auto_20210211_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='skills',
            field=models.ManyToManyField(to='crud_skills.Skills'),
        ),
    ]
